//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatelliteServer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SatelliteEntities : DbContext
    {
        public SatelliteEntities()
            : base("name=SatelliteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Incident> Incidents { get; set; }
        public virtual DbSet<Link> Links { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
    }
}
